version: '3'
services:
  app:
    #restart: always
    build: .
    working_dir: /app
    #volumes:
    #  - '~/.m2:/root/.m2'
    ports:
      - '9090:9090'
    command: './mvnw clean spring-boot:run'
    links:
      - mysql
  mysql:
    container_name: some-mysql
    image: 'mysql/mysql-server:5.7'
    environment:
      MYSQL_DATABASE: ticket
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      SPRING_JDBC_URL: jdbc:mysql://mysql:3306/ticket
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - my-db:/var/lib/mysql
    # Names our volume
volumes:
      my-db:
